---
- hosts: fortiswitches
  connection: httpapi
  collections:
    - fortinet.fortiswitch
  gather_facts: 'no'
  vars:
    ansible_httpapi_use_ssl: yes
    ansible_httpapi_validate_certs: no
    ansible_httpapi_port: 443

  tasks:

    - name: Configure management.
      fortinet.fortiswitch.fortiswitch_switch_vlan:
          state: "present"
          switch_vlan:
            id: "2"
            description: "Management"

    - name: Configure IOT.
      fortinet.fortiswitch.fortiswitch_switch_vlan:
          state: "present"
          switch_vlan:
            id: "3"
            description: "IOT"     

    - name: Configure management interface.
      fortiswitch_system_interface:
        state: present
        system_interface:
          name: vlan_2
          vdom: root
          allowaccess:
            - https
            - http
            - ssh
            - ping
            - snmp
          ip: "{{ ansible_host }} 255.255.255.0"
          vlanid: 2
          interface: "internal"
          alias: "Management"
          defaultgw: "enable"

    - name: IPv4 static route for Internet access.
      fortinet.fortiswitch.fortiswitch_router_static:
          state: "present"
          router_static:
              comment: "Management gateway"
              device: "vlan-2"
              gateway: " {{ dns_secondary }}"
              dst: "0.0.0.0/0"
              gw_l2_switch: "enable"
              seq_num: "1"
              status: "enable"

    - name: SNMP system info configuration.
      fortinet.fortiswitch.fortiswitch_system_snmp_sysinfo:
        system_snmp_sysinfo:
          contact_info: "{{ snmp_contact }}"
          description: "{{ inventory_hostname }}"
          location: "{{ location }}"
          status: "enable"

    - name: Configure global range attributes.
      fortinet.fortiswitch.fortiswitch_system_global:
        system_global:
          hostname: "{{ inventory_hostname }}"

    - name: Configure DNS
      fortinet.fortiswitch.fortiswitch_system_dns:
        system_dns:
          cache_notfound_responses: "enable"
          dns_cache_limit: "5000"
          dns_cache_ttl: "1800"
          domain: "{{ domain }}"
          primary: "{{ dns_primary }}"
          secondary: "{{ dns_secondary }}"

    - name: Ntp system info configuration
      fortinet.fortiswitch.fortiswitch_system_ntp:
        system_ntp:
          log_time_adjustments: "enable"
          ntpserver:
            - id: "1"
              server: "time.cloudflare.com"
            - id: "2"
              server: "time.google.com"
          ntpsync: "enable"
          server_mode: "enable"
          source_ip: "{{ ansible_host }}"
          syncinterval: "20"

    - name: SNMP user configuration.
      fortinet.fortiswitch.fortiswitch_system_snmp_user:
          state: "present"
          system_snmp_user:
              auth_proto: "sha256"
              auth_pwd: "{{ snmp_auth_password }}"
              name: "{{ snmp_user }}"
              notify_hosts: " {{ snmp_host }}"
              priv_proto: "aes256"
              priv_pwd: "{{ snmp_auth_password }}"
              queries: "enable"
              query_port: "161"
              security_level: "auth-priv"