# Workflow to deploy to a test environment and then to production
name: Deploy

# Run on push to main
on:
  push:
    branches: [ "main" ]

  # Allow manual runs
  workflow_dispatch: 

jobs:
#  deploy-ota:
#          # The type of runner that the job will run on
#    runs-on: self-hosted
#    steps:
      #      - name: Run FortiManager playbook
      #        run: ansible-playbook -i vars/hosts play-fortimanager.yml
#      - name: Run Fortiswitch playbook
#        run: ansible-playbook -i vars/hosts-ota play-fortiswitch.yml

  deploy-prod:
    runs-on: self-hosted
#    needs: deploy-ota

    steps:
      - name: Run Fortiswitch playbook
        run: ansible-playbook -i /home/pi/vars/ftnt_lab/hosts-prod play-fortiswitch.yml