# Workflow to deploy to a test environment and then to production
name: Deploy

# Run on push to main
on:
  push:
    branches: [ "main" ]

  # Allow manual runs
  workflow_dispatch: 

jobs:

  build:
    name: Ansible Lint # Naming the build is important to use it as a status check
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Run ansible-lint
        uses: ansible/ansible-lint@main
        # optional (see below):
        with:
          args: ""
          setup_python: "true"
          working_directory: ""
          requirements_file: ""


#  deploy-ota:
#          # The type of runner that the job will run on
#    runs-on: self-hosted
#    needs: build
#    steps:
      #      - name: Run FortiManager playbook
      #        run: ansible-playbook -i vars/hosts play-fortimanager.yml
#      - name: Run Fortiswitch playbook
#        run: ansible-playbook -i vars/hosts-ota play-fortiswitch.yml

  deploy-prod:
    runs-on: self-hosted
    needs: build
#    needs: deploy-ota

    steps:
      - uses: actions/checkout@v2
      - name: Run Fortiswitch playbook
        run: ansible-playbook -i /home/pi/vars/ftnt_lab/hosts-prod play-fortiswitch.yml